    <div id="recover-page">

      <!-- Caso aconteça algum erro -->
      <?php echo (isset($this->alert)?$this->alert:''); ?>

      <div class="container">
      
          <form class="form-login" method="post" action="<?php echo BASE; ?>recover/change-password/<?php echo $view_token; ?>">
            <h2 class="form-login-heading">Redefinição de senha</h2>
            <div class="login-wrap">

                <label>Nova senha:</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Informe sua nova senha" autofocus>
                <br>
                
                <button class="btn btn-theme btn-block" type="submit"><i class="fa"></i>Alterar minha senha</button>

            </div>
    
          </form>     
      
      </div>
    </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="<?php echo DASHGUM; ?>js/jquery.js"></script>
    <script src="<?php echo DASHGUM; ?>js/bootstrap.min.js"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="<?php echo DASHGUM; ?>js/jquery.backstretch.min.js"></script>
    <script>
        $.backstretch("<?php echo DASHGUM; ?>img/background.jpg", {speed: 500});
    </script>
