<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">

    <title><?php echo $view_title; ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo DASHGUM; ?>css/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="<?php echo DASHGUM; ?>font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="<?php echo DASHGUM; ?>css/zabuto_calendar.css?v=2">
    <link rel="stylesheet" type="text/css" href="<?php echo DASHGUM; ?>js/gritter/css/jquery.gritter.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo DASHGUM; ?>lineicons/style.css">    
    
    <!-- Para os gráficos morris -->
    <link rel="stylesheet" type="text/css" href="<?php echo DASHGUM; ?>css/morris-0.4.3.min.css">

    <!-- Custom styles for this template -->
    <link href="<?php echo DASHGUM; ?>css/style.css?v=6" rel="stylesheet">
    <link href="<?php echo DASHGUM; ?>css/style-responsive.css" rel="stylesheet">

    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon.png" type="image/x-icon">

    <script src="<?php echo DASHGUM; ?>js/chart-master/Chart.js"></script>
    
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    