<section id="container" >
      <?php echo (isset($this->alert)?$this->alert:''); ?>

      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>DASHGUM FREE</b></a>
            <!--logo end-->
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="<?php echo BASE; ?>login/logout/">Sair</a></li>
                </ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
        <div id="sidebar"  class="nav-collapse ">
          <!-- sidebar menu start-->
          <ul class="sidebar-menu" id="nav-accordion">

            <p class="centered">
              <a href="<?php echo BASE; ?>profile/edit/">
                <img title="Alterar minhas informações" src="<?php echo IMG_UPLOAD; ?>users/<?php echo (!is_null($view_user->image)) ? $view_user->id . '/' . $view_user->image : 'img_default_user.png' ;?>" class="img-circle" width="60">
              </a>
            </p>
            <h5 class="centered"><?php echo strtoupper($view_user->name); ?></h5>

          <?php echo (isset($this->menu) ? $this->menu : ''); ?>
      </aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
		<section id="main-content">
			<section class="wrapper">
			
			<div class="row mt">
				<div class="col-md-12">
					<div class="content-panel"> <!-- panel-body -->
						<table class="table table-striped table-advance table-hover">
							<h4><i class="fa fa-angle-right"></i> Usuários cadastrados no sistema</h4>
							<thead>
								<tr>
									<th><i class=" fa fa-user"></i> Nome</th>
									<th><i class=" fa fa-envelope-o"></i> E-mail</th>
									<th><i class=" fa fa-sign-in"></i> Login</th>
									<th><i class=" fa fa-exclamation-triangle"></i> Nível</th>
									<th><i class=" fa fa-edit"></i> Ações</th>
								</tr>
							</thead>
							<tbody>
								<?php
									if ($view_users) :
										foreach ($view_users as $user) :
								?>
										<tr>
											<td><?php echo $user->name ?></td>
											<td><?php echo $user->email ?></td>
											<td><?php echo $user->username ?></td>
											<td><?php echo "<span class='label label-mini "; echo $user->role_id == 1? "label-success'> Administrador": "label-info'> Usuário"; ?></span></td>
											<td>
												<?php if($user->status === 0) : ?>
													<a href="<?php echo BASE . 'users/unlockUser/' . $user->id; ?>" class="btn btn-xs btn-success">
														<i class="fa fa-unlock"></i> Desbloquear
													</a>
												<?php else : ?>
													<a href="<?php echo BASE . 'users/lockUser/' . $user->id; ?>" class="btn btn-xs btn-warning">
														<i class="fa fa-lock"></i> Bloquear
													</a>
												<?php endif; ?>
												
												<a href="<?php echo BASE . 'users/deleteUser/' . $user->id; ?>" class="btn btn-xs btn-danger">
													<i class="fa fa-trash"></i> Excluir
												</a>
											</td>
										</tr>
								<?php
										endforeach;
									endif;
								?>
							</tbody>
						</table>
					</div> <!-- content-panel -->
				</div> <!-- col-md-12 -->
			</div>
			
			</section>
		</section>
		<!--main content end-->
	  
      <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2017 - Harllan A.
          </div>
      </footer>
      <!--footer end-->
</section>

<!-- js placed at the end of the document so the pages load faster -->
<script src="<?php echo DASHGUM; ?>js/jquery.js"></script>
<script src="<?php echo DASHGUM; ?>js/bootstrap.min.js"></script>
<script class="include" type="text/javascript" src="<?php echo DASHGUM; ?>js/jquery.dcjqaccordion.2.7.js"></script>
<script src="<?php echo DASHGUM; ?>js/jquery.scrollTo.min.js"></script>
<script src="<?php echo DASHGUM; ?>js/jquery.nicescroll.js" type="text/javascript"></script>

<!--common script for all pages-->
<script src="<?php echo DASHGUM; ?>js/common-scripts.js"></script>

