<section id="container" >
      <?php echo (isset($this->alert)?$this->alert:''); ?>
  
      <script type="text/javascript">
        function disableIncome(exists_income){
          var activate = ((exists_income === null) || (typeof exists_income === 'undefined')) ? false : true;
          document.getElementById("incomeAmount").disabled = activate;
          document.getElementById("additional").disabled = activate;
          document.getElementById("month").disabled = activate;
          document.getElementById("btnSalve").disabled = activate;
          //console.log(exists_income);
        }
      </script>

      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>DASHGUM FREE</b></a>
            <!--logo end-->
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="<?php echo BASE; ?>login/logout/">Sair</a></li>
                </ul>
            </div>
        </header>
      <!--header end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
      <!--sidebar start-->
      <aside>
        <div id="sidebar"  class="nav-collapse ">
          <!-- sidebar menu start-->
          <ul class="sidebar-menu" id="nav-accordion">

            <p class="centered">
              <a href="<?php echo BASE; ?>profile/edit/">
                <img title="Alterar minhas informações" src="<?php echo IMG_UPLOAD; ?>users/<?php echo (!is_null($view_user->image)) ? $view_user->id . '/' . $view_user->image : 'img_default_user.png' ;?>" class="img-circle" width="60">
              </a>
            </p>
            <h5 class="centered"><?php echo strtoupper($view_user->name); ?></h5>

          <?php echo (isset($this->menu) ? $this->menu : ''); ?>
      </aside>
      <!--sidebar end-->
      
      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">

              <div class="row mt">
                  <div class="col-lg-12 main-chart"> <!-- "col-lg-9" deixa os forms em três colunas -->
                  
                    <!-- <div class="row mt"> -->
                        <div class="col-lg-4">
                              <div class="form-panel">
                                    <h4 class="mb"><i class="fa fa-angle-right"></i> Cadastro de despesas</h4>
                                    <form class="form-horizontal style-form" method="post" action="<?php echo BASE; ?>expenses/registerExpenses/">
                                          <label>Descrição:</label>
                                          <input type="text" class="form-control" name="description" id="description" placeholder="ex.: compras do mês" autofocus>
                                          </br>
                                          <label>Grupo:</label>
                                          <select name="group" id="group" class="form-control">
                                                <?php $arrComboGroup = GroupExpenses::searchAllGroups(); ?>
                                                <?php foreach ($arrComboGroup as $key => $value): ?>
                                                <?php echo "<option value=\"$key\" >$value</option>"; ?>
                                                <?php endforeach; ?>
                                          </select>
                                          </br>
                                          <label>Valor (R$):</label>
                                          <input type="number" class="form-control" name="amount" id="amount" placeholder="ex.: 325,15" step="0.01" min="0">
                                          </br>
                                          <label>Data da despesa:</label>
                                          <input type="date" class="form-control" name="date" id="date" value="<?php echo date('Y-m-d'); ?>">
                                          
                                          </br>
                                          <button class="btn btn-theme btn-block" type="submit"><i class="fa"></i>CADASTRAR</button>
                                    </form>
                              </div>
                        </div>

                      <!-- RENDA/SALÁRIO -->
                      <div class="col-lg-4">
                              <div class="form-panel">
                                    <h4 class="mb"><i class="fa fa-angle-right"></i> Cadastro da renda mensal</h4>
                                    <form class="form-horizontal style-form" method="post" action="<?php echo BASE; ?>expenses/registerIncome/">
                                          <?php
                                                $incomeUser = IncomeUsers::searchUserIncome($view_user->id);
                                                // echo "<pre>"; var_dump($incomeUser); echo "</pre>;"
                                          ?>
                                          <script type="text/javascript">
                                                window.onload = function() {
                                                      disableIncome(<?php echo $incomeUser['amount']; ?>);
                                                };
                                          </script>
                                          <label>Salário:</label>
                                          <input type="number" class="form-control" name="incomeAmount" id="incomeAmount" placeholder="ex.: 3500,00" step="0.01" min="0" value="<?php echo !is_null($incomeUser['amount']) ? $incomeUser['amount'] : ''; ?>">
                                          </br>
                                          <label>Adicional:</label>
                                          <input type="number" class="form-control" name="additional" id="additional" placeholder="ex.: 1500,00" step="0.01" min="0" value="<?php echo !is_null($incomeUser['additional']) ? $incomeUser['additional'] : ''; ?>">
                                          </br>
                                          <label>Mês:</label>
                                          <input type="number" class="form-control" name="month" id="month" step="1" min="1" max="12" value="<?php echo !is_null($incomeUser['month']) ? $incomeUser['month'] : (int) date('m'); ?>">
                                          
                                          </br>
                                          <button class="btn btn-theme btn-block" type="submit" id="btnSalve"><i class="fa fa-check-square-o"></i> SALVAR</button>
                                          <button class="btn btn-theme btn-block" type="button" onclick="disableIncome(null);"><i class="fa fa-pencil-square-o"></i> EDITAR</button>
                                    </form>
                              </div>
                        </div>

                        <!-- CADASTRO DOS GRUPOS -->
                        <div class="col-lg-4">
                              <div class="form-panel">
                                    <h4 class="mb"><i class="fa fa-angle-right"></i> Cadastro de grupos</h4>
                                    <form class="form-horizontal style-form" method="post" action="<?php echo BASE; ?>expenses/registerGroup/">
                                          <label>Novo grupo:</label>
                                          <input type="text" class="form-control" name="name" id="name" placeholder="ex.: Lazer">
                                          </br>
                                          <button class="btn btn-theme btn-block" type="submit"><i class="fa"></i>CADASTRAR</button>
                                    </form>
                              </div>
                        </div>

                    <!-- </div> -- class=row -->

                  </div> <!-- /col-lg-12 -->
              </div> <!--/row -->
              
          </section> <!-- wrapper -->
      </section>
      <!--main content end-->
      
      <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2017 - Harllan A.
          </div>
      </footer>
      <!--footer end-->
  </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="<?php echo DASHGUM; ?>js/jquery.js"></script>
    <script src="<?php echo DASHGUM; ?>js/jquery-1.8.3.min.js"></script>
    <script src="<?php echo DASHGUM; ?>js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="<?php echo DASHGUM; ?>js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="<?php echo DASHGUM; ?>js/jquery.scrollTo.min.js"></script>
    <script src="<?php echo DASHGUM; ?>js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="<?php echo DASHGUM; ?>js/jquery.sparkline.js"></script>


    <!--common script for all pages-->
    <script src="<?php echo DASHGUM; ?>js/common-scripts.js"></script>
    <script type="text/javascript" src="<?php echo DASHGUM; ?>js/gritter/js/jquery.gritter.js"></script>
    <script type="text/javascript" src="<?php echo DASHGUM; ?>js/gritter-conf.js"></script>

