	<!-- Carregar o relógio na tela -->
	<script type="text/javascript">
        window.onload = function() { getTime(); };
    </script>

      <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

	  	<div class="container">
	  	
	  		<div id="showtime"></div>
			<div class="col-lg-4 col-lg-offset-4">
				<div class="lock-screen">
					<!-- <h2><a data-toggle="modal" href="#signin"><i class="fa fa-lock"></i></a></h2> -->
					<h2><a href="home"><i class="fa fa-lock"></i></a></h2>
					<p>UNLOCK</p>
					
					  <!-- Modal -->
					  <!-- <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="signin" class="modal fade">
						<form action="home" method="post">
						  <div class="modal-dialog">
							  <div class="modal-content">
								  <div class="modal-header">
									  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
									  <h4 class="modal-title">Bem-vindo novamente</h4>
								  </div>
								  <div class="modal-body">
									  <p class="centered"><img class="img-circle" width="80" src="<?php //echo DASHGUM; ?>img/uploads/users/<?php //echo (!is_null($view_user->image)) ? $view_user->id . '/' . $view_user->image : 'img_default_user.png' ;?>"></p>
									  <input type="password" name="password" placeholder="Digite sua senha" autocomplete="off" class="form-control placeholder-no-fix">
			
								  </div>
								  <div class="modal-footer centered">
									  <button data-dismiss="modal" class="btn btn-theme04" type="button">Cancelar</button>
									  <button class="btn btn-theme03" type="submit">Entrar</button>
								  </div>
							  </div>
						  </div>
						</form>
					  </div> -->
					  <!-- modal -->
					
					
				</div> <!-- /lock-screen -->
			</div><!-- /col-lg-4 -->
	  	
	  	</div><!-- /container -->

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="<?php echo DASHGUM; ?>js/jquery.js"></script>
    <script src="<?php echo DASHGUM; ?>js/bootstrap.min.js"></script>

    <!--BACKSTRETCH-->
    <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
    <script type="text/javascript" src="<?php echo DASHGUM; ?>js/jquery.backstretch.min.js"></script>
    <script>
        //$.backstretch("<?php echo DASHGUM; ?>img/login-bg.jpg", {speed: 500});
		$.backstretch("<?php echo DASHGUM; ?>img/background.jpg", {speed: 500});
    </script>

    <script>
        function getTime()
        {
            var today=new Date();
            var h=today.getHours();
            var m=today.getMinutes();
            var s=today.getSeconds();
            // add a zero in front of numbers<10
            m=checkTime(m);
            s=checkTime(s);
            document.getElementById('showtime').innerHTML=h+":"+m+":"+s;
            t=setTimeout(function(){getTime();},500);
        }

        function checkTime(i)
        {
            if (i<10)
            {
                i="0" + i;
            }
            return i;
        }
    </script>

